### ISSUE TITLE
Drupal Bootstrap could not complete successfully.

### ISSUE THREAD

**Issue by syui** [Gizra/generator-hedley#111]
```bash
$ git clone https://github.com/Gizra/generator-hedley
$ cd generator-hedley
$ chmod +x install
$ ./install
drush status grep "Drupal bootstrap" | grep "Successful"
```

## console log

```bash
exception 'Exception' with message 'Resolve all issues below to continue the installation. For help configuring your       [error]
database server, see the <a href="http://drupal.org/getting-started/install">installation handbook</a>, or contact your
hosting provider.<p class="error">Failed to connect to your database server. The server reports the following message:
<em>SQLSTATE[HY000] [2002] No route to host</em>.<ul><li>Is the database server running?</li><li>Does the database exist,
and have you entered the correct database name?</li><li>Have you entered the correct username and password?</li><li>Have
you entered the correct database hostname?</li></ul></p>' in
$HOME/generator-hedley/www/includes/install.core.inc:415
Stack trace:
#0 $HOME/generator-hedley/www/includes/install.core.inc(339): install_run_task(Array, Array)
#1 $HOME/blog/generator-hedley/www/includes/install.core.inc(77): install_run_tasks(Array)
#2 $HOME/.composer/vendor/drush/drush/includes/drush.inc(725): install_drupal(Array)
#3 $HOME/.composer/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#4 $HOME/.composer/vendor/drush/drush/commands/core/drupal/site_install_7.inc(82): drush_op('install_drupal', Array)
#5 $HOME/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(247):
drush_core_site_install_version('hedley', Array)
#6 [internal function]: drush_core_site_install('hedley')
#7 $HOME/.composer/vendor/drush/drush/includes/command.inc(366): call_user_func_array('drush_core_site...', Array)
#8 $HOME/.composer/vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#9 [internal function]: drush_command('hedley')
#10 $HOME/.composer/vendor/drush/drush/includes/command.inc(185): call_user_func_array('drush_command', Array)
#11 $HOME/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#12 $HOME/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 $HOME/.composer/vendor/drush/drush/drush.php(12): drush_main()
#14 {main}

> Set the file permissions on the sites/default/files directory

> Enabling the development modules
Command pm-enable needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal      [error]
environment to run this command.
The drush command 'en devel views_ui field_ui' could not be executed.                                                      [error]
Drush was not able to start (bootstrap) the Drupal database.                                                               [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another
site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush
topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed
shell. See http://drupal.org/node/1428638 for details.

Drush was attempting to connect to:
 Drupal version         :  7.43
 Site URI               :  http://default
 PHP executable         :  /usr/local/bin/php
 PHP configuration      :  /usr/local/etc/php/5.5/php.ini
 PHP OS                 :  Darwin
 Drush script           :  $HOME/.composer/vendor/drush/drush/drush.php
 Drush version          :  8.1.2
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :
 Drupal root            :  $HOME/generator-hedley/www
 Drupal Settings File   :  sites/default/settings.php
 Site path              :  sites/default

> Run post_install script.

  Installation failure!
  > Drupal Bootstrap could not complete successfully.
```

I am hosting a drupal to the pantheon.

http://dev-syui.pantheonsite.io/

I made a page on GitHub.

https://syui.github.io/elm-hedley/

> src/elm/Config.elm

```js
// https://github.com/Gizra/elm-hedley/commit/f374a3b1680b16d1d3b0f722a74c7c82f28b4f6a#diff-12275ec22d3941822667dda3d8c44b44L8
prodBackend : BackendConfig
prodBackend =
  { backendUrl = "http://dev-syui.pantheonsite.io"
  , githubClientId = "xxxxxxxxxxxxxxx"
  , name = "gh-pages"
  , hostname = "syui.github.io"
  }
```

However, it does not end load.

Bootstrap will seem like it is not functioning.

```bash
$ git clone https://github.com/Gizra/hedley-server
$ cd hedley-server
$ ./install
$ rm www/profiles/hedley
$ cp -rf ./hedley www/profiles
$ rm www/.gitignore
$ cd www
# pantheon upload
$ git init ... git push
```

SFTP mode, and change the permissions on the settings.php to 644.

https://pantheon.io/docs/filesystem-faq/

```bash
$ sftp -o Port=2222 dev.foo...
$ cd /code/site/default
$ chmod 644 settings.php
```

Please let me know if there are any issues.

Thanks!

**Comment by syui** [comment]
The problem has been resolved.

**Comment by amitaibu** [comment]
👍

**Comment by syui** [comment]
Thx!
