### ISSUE TITLE
Issues on Windows

### ISSUE THREAD

**Issue by cosmicdreams** [Gizra/generator-hedley#19]
When I execute:

$ yo hedley --skip-install --project-name=skeleton --github-repo=https://github.com/drupal/drupal.git --db=skeleton --db-user=root --db-pass=root --drupal-url=http://localhost/skeleton/www

I get the following error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
AssertionError: **C:\Users\cweber\AppData\Roaming\npm\node_modules\generator-hedley\app\templates\C:\Users\cweber\AppData\Roaming\npm\node_modules\generator-hedley\app\templates\README.md** doesn't exist
    at EditionInterface.module.exports [as read](C:UserscweberAppDataRoamingnpmnode_modulesgenerator-hedleynode_modulesyeoman-generatornode_modulesmem-fs-editoractionsread.js:9:3)
    at C:\Users\cweber\AppData\Roaming\npm\node_modules\generator-hedley\app\index.js:242:34
    at Array.forEach (native)
    at module.exports.yeoman.generators.Base.extend.writing.app (C:\Users\cweber\AppData\Roaming\npm\node_modules\generator-hedley\app\index.js:212:13)
    at C:\Users\cweber\AppData\Roaming\npm\node_modules\generator-hedley\node_modules\yeoman-generator\lib\base.js:406:16
    at processImmediate [as _immediateCallback](timers.js:330:15)

This may be due to how the the system understands files / directories.  Have you accounted for Windows environments?

**Comment by amitaibu** [comment]
@cosmicdreams were you able to check the problem?

**Comment by aarondanielson** [comment]
Same problem here :|

**Comment by jmdall** [comment]
Same for me !

**Comment by amitaibu** [comment]
Never knew there where so many devs on windows out there ;)

@aarondanielson @jmdall are you able to confirm if indeed the problem is around this [line](https://github.com/Gizra/generator-hedley/blob/master/app/index.js#L224)

**Comment by jmdall** [comment]
Tried to run on debug mode and seems to be on this [line](https://github.com/Gizra/generator-hedley/blob/master/app/index.js#L212).

So yeah it's around yours, a bit before.

Thanks !

**Comment by amitaibu** [comment]
@jmdall any chance for a PR to fix it? :)

**Comment by jmdall** [comment]
What does mean PR ?

**Comment by amitaibu** [comment]
Pull request - a fix to the existing code

**Comment by jmdall** [comment]
Not sure to have enough time but I'll try

**Comment by jmdall** [comment]
Now there's more problems but further on Drupal install.
